server:
  port: 9000

spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    url: jdbc:mysql://localhost:3306/pharmacy?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: jennny2001

qiniu:
  accessKey:
  secretKey:
  bucket:
  host:
  zone:

oss:
  accessKey: REDACTED
  secretKey: REDACTED
  endpoint: oss-cn-shenzhen.aliyuncs.com
  host: recruit1
