# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/pharmacy?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:myPassword}  # Replace "jennny2001" with your secure value via env var

  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /statics/**

  # Redis configuration
  redis:
    database: 0           # Redis server database
    host: 127.0.0.1       # Redis server address
    port: 6379            # Redis server connection port
    password: ${REDIS_PASSWORD:}   # Leave empty if no password
    timeout: 6000ms       # Connection timeout in milliseconds
    jedis:
      pool:
        max-active: 200   # Maximum number of active connections in the pool (negative means unlimited)
        max-wait: -1      # Maximum wait time for a connection (negative means unlimited)
        max-idle: 10      # Maximum number of idle connections
        min-idle: 0       # Minimum number of idle connections

  # Mail configuration
  mail:
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}   # Authorization password, not the actual email password
    host: smtp.qq.com             # SMTP server
    protocol: smtp                # Email protocol
    default-encoding: utf-8
    port: 465
    properties.mail.smtp.ssl.enable: true  # Enable SSL for SMTP

  # File upload configuration
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 10MB

# MyBatis-Plus configuration
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  global-config:
    db-config:
      #logic-delete-field: deleted  # Uncomment if you want to set a custom field
      logic-delete-value: 1         # Value representing a deleted record
      logic-not-delete-value: 0     # Value representing a non-deleted record

# JWT configuration
yjx:
  jwt:
    secret: ${JWT_SECRET:your_jwt_secret_here}  # Set your JWT secret via an environment variable
    expire: 604800  # Token expiration time in seconds (1 week)
    header: Authorization

# Logging configuration
logging:
  level:
    com:
      yjx: debug

# Jasypt encryption configuration
jasypt:
  encryptor:
    password: ${JASYPT_PASSWORD:your_jasypt_password_here}  # Set Jasypt decryption password via env var